# Programs & Pricing (Plans)
programs:
  - name: "Technology Maker"
    price: $149
    unit: "month"
    sessions_per_month: 4
    description: "Includes 4 sessions/month. Choose Coding, Robotics, or AI projects."
  - name: "Math Master"
    price: $149
    unit: "month"
    sessions_per_month: 24
    description: "Includes 4 sessions/month. Master Mathmatics, build strong foundations using Alberta Math methods."
    featured: true  # Most popular
  - name: "1-1 Private"
    price: $49
    unit: "session"
    sessions_per_month: 1
    description: "Individual sessions to build strong foundations using Alberta Math methods."

# Discounts
discounts:
  sibling: "10% off additional siblings enrolled together."
  referral: "$25 referral credit for both families when you refer a friend."
